revised CD v3

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -80,7 +80,7 @@ jobs:
             --region "$AWS_REGION" \
             --parameters "commands=[
             \"sudo -iu ubuntu bash -c 'cd /home/ubuntu/chat-bot && export BACKEND_IMAGE=$IMAGE && aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY && docker compose pull backend celery && docker compose up -d --force-recreate backend celery'\",
-            \"sudo -iu ubuntu bash -c 'CURRENT_IMAGE=\\\"$IMAGE\\\"; echo Current image: \\$CURRENT_IMAGE; docker images \\\"$ECR_REGISTRY\\\" --format \\\"{{.Repository}}:{{.Tag}}\\\" | while IFS= read -r image; do if [ \\\"\\$image\\\" != \\\"\\$CURRENT_IMAGE\\\" ]; then echo \\\"Removing \\$image\\\"; docker rmi \\\"\\$image\\\" || true; fi; done'\"
+            \"sudo -iu ubuntu bash -c 'CURRENT_IMAGE=\\\"$IMAGE\\\"; echo Current image: \\$CURRENT_IMAGE; echo Images before cleanup:; docker images \\\"$ECR_REGISTRY\\\" --format \\\"{{.Repository}}:{{.Tag}}\\\"; for image in \\$(docker images \\\"$ECR_REGISTRY\\\" --format \\\"{{.Repository}}:{{.Tag}}\\\"); do if [ \\\"\\$image\\\" != \\\"\\$CURRENT_IMAGE\\\" ]; then echo Removing \\\"\\$image\\\"; docker rmi \\\"\\$image\\\" || true; fi; done; echo Images after cleanup:; docker images \\\"$ECR_REGISTRY\\\" --format \\\"{{.Repository}}:{{.Tag}}\\\"'\"
           ]" \
             --query "Command.CommandId" \
             --output text)
@@ -99,13 +99,24 @@ jobs:
 
           echo "Deployment status: $STATUS"
 
+          echo "----- SSM OUTPUT -----"
+
+          aws ssm get-command-invocation \
+            --command-id "$COMMAND_ID" \
+            --instance-id "$EC2_INSTANCE_ID" \
+            --query "StandardOutputContent" \
+            --output text
+
+          echo "----- SSM ERROR -----"
+
+          aws ssm get-command-invocation \
+            --command-id "$COMMAND_ID" \
+            --instance-id "$EC2_INSTANCE_ID" \
+            --query "StandardErrorContent" \
+            --output text
+
           if [ "$STATUS" != "Success" ]; then
             echo "Deployment failed"
-
-            aws ssm get-command-invocation \
-              --command-id "$COMMAND_ID" \
-              --instance-id "$EC2_INSTANCE_ID"
-
             exit 1
           fi
 
